---
# Builds and runs the Thorlabs T/KCube control services
name: thorlabs_kcube_control

services:
    ablation_y:
        container_name: kdc101_0
        restart: always
        ports:
            - 3255:3255
        devices:
            - /dev/kdc101_0:/dev/ttyUSB0
        networks:
            - thorlabs_cube
        build:
            context: ./
            dockerfile: ./Dockerfile
        # to run in simulation mode, include "--simulation"
        # in the entrypoint command after port number
        entrypoint: [aqctl_thorlabs_cube]
        command: [-p, '3255', -P, kdc101, -d, /dev/ttyUSB0, --bind, '*']

    ablation_z:
        container_name: kdc101_1
        restart: always
        ports:
            - 3256:3255
        devices:
            - /dev/kdc101_1:/dev/ttyUSB0
        networks:
            - thorlabs_cube
        build:
            context: ./
            dockerfile: ./Dockerfile
        entrypoint: [aqctl_thorlabs_cube]
        command: [-p, '3255', -P, kdc101, -d, /dev/ttyUSB0, --bind, '*']

    photoionization_z:
        container_name: kpz101_0
        restart: always
        ports:
            - 3257:3255
        devices:
            - /dev/kpz101_0:/dev/ttyUSB0
        networks:
            - thorlabs_cube
        build:
            context: ./
            dockerfile: ./Dockerfile
        entrypoint: [aqctl_thorlabs_cube]
        command: [-p, '3255', -P, kdc101, -d, /dev/ttyUSB0, --bind, '*']

    crm_z:
        container_name: kpz101_1
        restart: always
        ports:
            - 3258:3255
        devices:
            - /dev/kpz101_1:/dev/ttyUSB0
        networks:
            - thorlabs_cube
        build:
            context: ./
            dockerfile: ./Dockerfile
        entrypoint: [aqctl_thorlabs_cube]
        command: [-p, '3255', -P, kdc101, -d, /dev/ttyUSB0, --bind, '*']

networks:
    thorlabs_cube:
