# builds and runs the thorlabs t/kcube control services
services:
  thorlabs_cube:
    container_name: kdc101
    # restart: always
    ports:
      - 3255:3255
    devices:
     - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - motor
    build:
      context: ./
      dockerfile: ./Dockerfile
    # to run in simulation mode, include "--simulation" in the entrypoint command after port number
    entrypoint: [ "aqctl_thorlabs_cube"]
    command: ["-p", "3255", "-P", "kdc101", "-d", "/dev/ttyUSB0", "--bind", "*"]

networks:
  motor:
