name: Code Quality

on:
  push:
    branches: [ "master", "cicd-init" ]
  pull_request:
    branches: [ "master", "cicd-init" ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package, flake8
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install flake8==7.0.0 flake8-bugbear==24.4.21 flake8-pyproject==1.2.3
          python -m pip install .
      - name: Setup and run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
      - name: Setup and run isort
        uses: isort/isort-action@master
        with:
          isortVersion: "5.13.2"
          sortPaths: "."
          configuration: "--check-only --diff --profile black --filter-files"
      - name: Setup and run flake8
        run: |
          flake8 .
