---
name: Code Quality

on:
  push:
    branches: ["master", "4-cicd-init"]
  pull_request:
    branches: ["master", "4-cicd-init"]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install flake8==7.0.0 flake8-bugbear==24.4.21
      - name: Setup and run black
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "./thorlabs_cube"
      - name: Setup and run isort
        uses: isort/isort-action@master
        with:
          isortVersion: "5.13.2"
          sortPaths: "./thorlabs_cube"
          configuration: "--check-only --diff --profile black --filter-files"
      - name: Setup and run flake8
        run: |
          flake8 ./thorlabs_cube
      - name: yamllint
        uses: karancode/yamllint-github-action@v2.1.1

  check-types:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install mypy and requirements
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install mypy==1.10.0
      - name: Run mypy
        run: |
          mypy ./thorlabs_cube --ignore-missing-imports
