---
name: Container

on:
  push:
    branches: ["master", "4-cicd-init"]
  pull_request:
    branches: ["master", "4-cicd-init"]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build container
        run: |
          docker compose build
