name: Documentation

on:
  push:
    branches: [ "master", "cicd-init" ]
  pull_request:
    branches: [ "master", "cicd-init" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install numpy
          python -m pip install sipyco@git+https://github.com/m-labs/sipyco.git asyncserial
          python -m pip install -U sphinx==7.3.7
          python -m pip install .
      - name: Build documentation
        run: |
          cd doc
          make html
